### ISSUE TITLE
Risk of thread blocked alert when waiting too long inside ResourceAdapterLifecycleListener hooks

### ISSUE THREAD

**Issue by vondacho** [quarkiverse/quarkus-ironjacamar#108]
The `ResourceAdapterLifecycleListener` interface has been recently developed in order to satisfy the need to perform some operations before or after is launched or shutdown, for example, [pausing the early JMS message consumption at application startup](https://github.com/quarkiverse/quarkus-ironjacamar/issues/103).

The current issue aims to raise the high risk of thread blocked warning by Vert.x if pausing too long at pre-startup or another hook, Vert.x usually raises an exception mentioning a maximal timeout threshold of 60000ms.

Similar to the Scheduler API, it would be welcome to be able to pause and resume an already started `ResourceAdpater `instance.

Regards

**Comment by gastaldi** [comment]
I need to investigate this, but my gut feeling says that it may depend if the ResourceAdapter implementation (Artemis in your case) supports such feature, as pausing is not defined in the JCA spec.

As a workaround, you can increase the warning exception time:
```properties
quarkus.vertx.warning-exception-time=5M
```

**Comment by gastaldi** [comment]
> As a workaround, you can increase the warning exception time:
> 
> ```ini
> quarkus.vertx.warning-exception-time=5M
> ```

Actually that information is not being used when deploying the Verticle, I'll submit a PR soon

**Comment by gastaldi** [comment]
Since we can't pause the adapter, I'll take that https://github.com/quarkiverse/quarkus-ironjacamar/commit/4f39701f7088f45155dfe7413a35bd7a397c4298 fixed the problem and close this issue. Feel free to reopen if that's not enough
