### ISSUE TITLE
listener does not support jta

### ISSUE THREAD

**Issue by vsevel** [quarkiverse/quarkus-ironjacamar#17]
with the following code, the message is normally consumed and it should not:
```
    @Override
    @Transactional(Transactional.TxType.REQUIRES_NEW)
    public void onMessage(Message message) {
        try {
            log.info("Received blue message: " + message.getBody(String.class));
            QuarkusTransaction.setRollbackOnly();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
 ```

whereas, this code will trigger a redeliver, which is expected:
```
    @Override
    public void onMessage(Message message) {
...
        throw new RuntimeException("oops");
    } 
```

**Comment by gastaldi** [comment]
That's because there isn't a transaction outside the `@Transactional` method. 

This is not something related to IronJacamar specifically, but a configuration in the Artemis RA (and the ResourceAdapterFactory) I believe

**Comment by gastaldi** [comment]
Actually, let me dig a little bit more. I think this is done through a `ConnectionEventListener` in the ManagedConnection, investigating

**Comment by gastaldi** [comment]
@tadamski any hints? Maybe I am missing something?

**Comment by gastaldi** [comment]
~~> This is not something related to IronJacamar specifically, but a configuration in the Artemis RA (and the ResourceAdapterFactory) I believe~~

Actually I take that back, the ManagedConnection is registered as part of the transaction but the transaction isn't started, I'll investigate more

**Comment by gastaldi** [comment]
@vsevel do you have any specific setting in your broker.xml? Trying to reproduce this in the `integration-tests/artemis-jms` project but I am unable to make it redeliver the message, even after throwing an exception

**Comment by tadamski** [comment]
@gastaldi I'm not sure if I understand the use case correctly, but it seems to me that ManagedConnection (and generally all the classes from "Connection Management" chapter from the spec are not relevant here as those are meant to be used in synchronous application server -> EIS invocations, which iiuc correctly is not the case here.

I think that relevant concepts are described in chapters "Message Inflow" and "Transaction Inflow". I reread those and there are two scenarios described:
* message endpoint starts a transaction after receive the message (all operations resulting from message processing are transacted 14.5.6)
* transaction is propagated from EIS to application server (chapter 16)

I assume this is a scenario one, and my understanding of the spec is that in such case it is message endpoint implementation which is responsible for starting and finishing the transaction

**Comment by gastaldi** [comment]
@tadamski thank you very much, I forgot to enlist the XAResource in the `MessageEndpointFactory.createEndpoint` to the active transaction. I have a PR in the works, I'd appreciate if you could review it

**Comment by vsevel** [comment]
> @tadamski thank you very much, I forgot to enlist the XAResource in the `MessageEndpointFactory.createEndpoint` to the active transaction. I have a PR in the works, I'd appreciate if you could review it

Great! I ill look at it today.
