### ISSUE TITLE
producer and consumer interceptors

### ISSUE THREAD

**Issue by vsevel** [quarkiverse/quarkus-ironjacamar#18]
provide example on how to configure message interceptor for send and consume use cases, similar to what is provided by smallrye messaging `PublisherDecorator` and `OutgoingInterceptor`.
cf https://smallrye.io/smallrye-reactive-messaging/4.1.0/concepts/decorators/

**Comment by gastaldi** [comment]
This is a Reactive Messaging feature and I don't think it makes sense to introduce this feature here since it's not really a JCA feature either. 

I added an example in the Reactive Messaging integration test demonstrating that it works
