### ISSUE TITLE
Support for duplicated context

### ISSUE THREAD

**Issue by vsevel** [quarkiverse/quarkus-ironjacamar#56]
The extension does not currently support duplicated context. Given the following code:
```
@ResourceEndpoint(activationSpecConfigKey = "myqueue")
@Identifier(Defaults.DEFAULT_RESOURCE_ADAPTER_NAME)
public class MyMessageEndpoint implements MessageListener {
    @Override
    public void onMessage(Message message) {
        try {
            Optional<Object> foo = ContextLocals.get("foo");
            Log.info("Received message: " + message.getBody(String.class) + " foo=" + foo);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
```

The following exception is thrown when receiving a message:
```
2023-09-29 14:31:22,927 ERROR [org.apa.act.art.ra.ActiveMQRALogger] (Thread-2 (ActiveMQ-client-global-threads)) AMQ154004: Failed to deliver 
message [Error Occurred After Shutdown]: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Access to Context Locals are fo
rbidden from a 'root' context  as it can leak data between unrelated processing. Make sure the method runs on a 'duplicated' (local) Context 
        at io.quarkiverse.ironjacamar.MyMessageEndpoint.onMessage(MyMessageEndpoint.java:21)
        at io.quarkiverse.ironjacamar.MyMessageEndpoint_ClientProxy.onMessage(Unknown Source)
        at io.quarkiverse.ironjacamar.artemis.ArtemisResourceAdapterFactory$JMSMessageEndpoint.onMessage(ArtemisResourceAdapterFactory.java:8
8)
        at org.apache.activemq.artemis.ra.inflow.ActiveMQMessageHandler.onMessage(ActiveMQMessageHandler.java:320)
        at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.callOnMessage(ClientConsumerImpl.java:982)
        at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl$Runner.run(ClientConsumerImpl.java:1134)
        at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:57)
        at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:32)
        at org.apache.activemq.artemis.utils.actors.ProcessorBase.executePendingTasks(ProcessorBase.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)
Caused by: java.lang.UnsupportedOperationException: Access to Context Locals are forbidden from a 'root' context  as it can leak data between
 unrelated processing. Make sure the method runs on a 'duplicated' (local) Context
        at io.smallrye.common.vertx.ContextLocals.ensureDuplicatedContext(ContextLocals.java:21)
        at io.smallrye.common.vertx.ContextLocals.get(ContextLocals.java:36)
        at io.quarkiverse.ironjacamar.MyMessageEndpoint.onMessage(MyMessageEndpoint.java:18)
        ... 11 more

```

**Comment by gastaldi** [comment]
@vsevel Considering that there is no previous context before the message is delivered, what would you expect to return when using the `ContextLocals` API?

**Comment by vsevel** [comment]
I would like to run on a duplicated context so that I can use ContexLocals get and put

**Comment by gastaldi** [comment]
You could do it in the listener or in the wrapped MessageEndpoint impl: https://github.com/quarkiverse/quarkus-ironjacamar/blob/main/runtime/src/main/java/io/quarkiverse/ironjacamar/ResourceAdapterFactory.java#L60.

If this is a common pattern perhaps we could do it in this extension, but I am not 100% sure TBH

**Comment by gastaldi** [comment]
Actually that involves calling your `onMessage` in a Vert.x context, which does not allow starting a JTA transaction from the IO thread, so I am still not sure how (and if) we can support that

**Comment by vsevel** [comment]
can you confirm @cescoffier ?
if you recall the issue at hand was getting a business correlation id from incoming requests (rest, kafka, jms, ...), install it into a request context, and push it down the line into outgoing communications (rest, kafka, jms, ...)
initially I had based on it on a request scope. 
then based in this other [conversation](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/kafka.20consumer.20interceptor/near/373097260) I moved from a request scope component to store this correlation id into a duplicated context using `ContextLocals.get/put`.
is there a way to get a consistent behavior between the blocking jms listener, reactive messaging and reactive resteasy?

**Comment by gastaldi** [comment]
The request scope is available during the listener invocation, so maybe you could create a `@RequestScoped` object instead of dealing with the Vert.x internals?

**Comment by vsevel** [comment]
> instead of dealing with the Vert.x internals?

I wish I could ;)

originally had a request scope bean to store my contextual information.
and I moved to the vertx context, based on the other conversation, because request scope is not supported in reactive messaging.
so I would need to manage 2 datastructures: 1 for jms (request scope approach), 1 for the rest (vertx context)?

so when I send the info during an outgoing communication I have to look into the vertx context and the request scope bean, as one or the other might have the info?

it is unfortunate we can't have a single _business transaction space_ (aka a thread local that works in all situations)

**Comment by cescoffier** [comment]
So, first having a duplicated context does not mean you can't block (example: virtual threads).

I have been thinking about our conversation about request scope for messages. I also discussed it with Ozan, and we see more drawbacks (merging, fan-out...) than benefits. A MessageScope looks more appropriate, but won't fix your issue. 

So I would recommend having this extension use duplicated context. Also, on which thread does it run? Does the extension manages its own thread pool?

**Comment by gastaldi** [comment]
> Also, on which thread does it run? Does the extension manages its own thread pool?

Yes, for inbound messages, the RA is free to manage its own threads, for outbound the spec requires using the WorkManager (which uses a `ManagedExecutor` internally)

**Comment by cescoffier** [comment]
That's annoying. It will be disconnected from the rest of Quarkus.

**Comment by vsevel** [comment]
> Also, on which thread does it run?

in my case `Thread-0 (ActiveMQ-client-global-threads)` 

I may have something that works. 
I store my business tx info into an object `WorkContext`. I have an optional request scope bean `WorkContextHolder` to hold onto it.
when in jms listener, I activate the request context on that bean, and store my info into it.
in other cases, the scope won't be active, I store my info into the `ContextLocals`.
when I want to retrieve my info, I look first in the `WorkContextHolder`, else info the `ContextLocals`.
I have tested only the 2 use cases:
- scheduler gets triggered, send kafka message, ... then receive kafka message
- scheduler gets triggered. send jms message, ... then receive jms message

this is way above my pay grade, and I fear I am going to miss some use cases.
another approach would be to piggy back on context propagation, assuming there would an api to adapt for incoming and outgoing communications.

**Comment by vsevel** [comment]
something strange in my kafka producer:
``` 
    @Outgoing("source-out")
    public Multi<Order> generate() {
        return Multi.createFrom().ticks().every(Duration.ofSeconds(5)).map(x -> createNewOrder());
    }

    Order createNewOrder() {
        try {
            ContextLocals.get("foo");
        } catch (UnsupportedOperationException e) {
            log.info("no context => " + e);
        }
``` 

will print:
```
no context => java.lang.UnsupportedOperationException: Access to Context Locals are forbidden from a 'root' context  as it can leak data between unrelated processing. Make sure the method runs on a 'duplicated' (local) Context
```

do I need to do anything to run with a duplicated context? I was assuming this would be done for me.

**Comment by cescoffier** [comment]
In this case, yes.

You are creating a streams yourself, not from a connector or emitter. Thus you do not have the duplicated context support.

**Comment by vsevel** [comment]
I think we can close this issue.
The question was answered in https://github.com/quarkiverse/quarkus-ironjacamar/issues/56#issuecomment-1741104091
I have implemented a workaround as described in https://github.com/quarkiverse/quarkus-ironjacamar/issues/56#issuecomment-1741285042
I let you @gastaldi if this https://github.com/quarkiverse/quarkus-ironjacamar/issues/56#issuecomment-1741276346 from @cescoffier mandates a separate issue
thanks for your help
